export const countries = [
  {
    fullname: 'Afghanistan',
    shortName: 'AFG',
    flag: '/assets/flags/af.svg',
    phoneCode: '+93',
  },
  {
    fullname: 'Aland Islands',
    shortName: 'ALA',
    flag: '/assets/flags/ax.svg',
    phoneCode: '+358',
  },
  {
    fullname: 'Albania',
    shortName: 'ALB',
    flag: '/assets/flags/al.svg',
    phoneCode: '+355',
  },
  {
    fullname: 'Algeria',
    shortName: 'DZA',
    flag: '/assets/flags/dz.svg',
    phoneCode: '+213',
  },
  {
    fullname: 'American Samoa',
    shortName: 'ASM',
    flag: '/assets/flags/as.svg',
    phoneCode: '+1 684',
  },
  {
    fullname: 'Andorra',
    shortName: 'AND',
    flag: '/assets/flags/ad.svg',
    phoneCode: '+376',
  },
  {
    fullname: 'Angola',
    shortName: 'AGO',
    flag: '/assets/flags/ao.svg',
    phoneCode: '+244',
  },
  {
    fullname: 'Anguilla',
    shortName: 'AIA',
    flag: '/assets/flags/ai.svg',
    phoneCode: '+1 264 ',
  },
  {
    fullname: 'Antarctica',
    shortName: 'ATA',
    flag: '/assets/flags/aq.svg',
    phoneCode: '', //******* NOT THERE ************** */
  },
  {
    fullname: 'Antigua and Barbuda',
    shortName: 'ATG',
    flag: '/assets/flags/ag.svg',
    phoneCode: '+1 268',
  },
  {
    fullname: 'Argentina',
    shortName: 'ARG',
    flag: '/assets/flags/ar.svg',
    phoneCode: '+54',
  },
  {
    fullname: 'Armenia',
    shortName: 'ARM',
    flag: '/assets/flags/am.svg',
    phoneCode: '+374',
  },
  {
    fullname: 'Aruba',
    shortName: 'ABW',
    flag: '/assets/flags/aw.svg',
    phoneCode: '+297',
  },
  {
    fullname: 'Australia',
    shortName: 'AUS',
    flag: '/assets/flags/au.svg',
    phoneCode: '+61',
  },
  {
    fullname: 'Austria',
    shortName: 'AUT',
    flag: '/assets/flags/at.svg',
    phoneCode: '+43',
  },
  {
    fullname: 'Azerbaijan',
    shortName: 'AZE',
    flag: '/assets/flags/az.svg',
    phoneCode: '+994',
  },
  {
    fullname: 'Bahamas',
    shortName: 'BHS',
    flag: '/assets/flags/bs.svg',
    phoneCode: '+1 242',
  },
  {
    fullname: 'Bahrain',
    shortName: 'BHR',
    flag: '/assets/flags/bh.svg',
    phoneCode: '+973',
  },
  {
    fullname: 'Bangladesh',
    shortName: 'BGD',
    flag: '/assets/flags/bd.svg',
    phoneCode: '+880',
  },
  {
    fullname: 'Barbados',
    shortName: 'BRB',
    flag: '/assets/flags/bb.svg',
    phoneCode: '+1 246',
  },
  {
    fullname: 'Belarus',
    shortName: 'BRL',
    flag: '/assets/flags/by.svg',
    phoneCode: '+375',
  },
  {
    fullname: 'Belgium',
    shortName: 'BEL',
    flag: '/assets/flags/be.svg',
    phoneCode: '+32',
  },
  {
    fullname: 'Belize',
    shortName: 'BLZ',
    flag: '/assets/flags/bz.svg',
    phoneCode: '+501',
  },
  {
    fullname: 'Benin',
    shortName: 'BEN',
    flag: '/assets/flags/bj.svg',
    phoneCode: '+299',
  },
  {
    fullname: 'Bermuda',
    shortName: 'BMU',
    flag: '/assets/flags/bm.svg',
    phoneCode: '+1 441',
  },
  {
    fullname: 'Bhutan',
    shortName: 'BTN',
    flag: '/assets/flags/bt.svg',
    phoneCode: '+975',
  },
  {
    fullname: 'Bolivia',
    shortName: 'BOL',
    flag: '/assets/flags/bo.svg',
    phoneCode: '+591',
  },
  {
    fullname: 'Bonaire, Sint Eusta...',
    shortName: 'BQ',
    flag: '/assets/flags/bq.svg',
    phoneCode: '+559 7',
  },
  {
    fullname: 'Bosnia and Herzegovina',
    shortName: 'BIH',
    flag: '/assets/flags/ba.svg',
    phoneCode: '+387',
  },
  {
    fullname: 'Botswana',
    shortName: 'BWA',
    flag: '/assets/flags/bw.svg',
    phoneCode: '+267',
  },
  {
    fullname: 'Bouvet Island',
    shortName: 'BVT',
    flag: '/assets/flags/bv.svg',
    phoneCode: '', //******* NOT THERE ************** */
  },
  {
    fullname: 'Brazil',
    shortName: 'BRA',
    flag: '/assets/flags/br.svg',
    phoneCode: '+55',
  },
  {
    fullname: 'British Indian Ocean Territory',
    shortName: 'IOT',
    flag: '/assets/flags/io.svg',
    phoneCode: '+246',
  },
  {
    fullname: 'Brunei Darussalam',
    shortName: 'BRN',
    flag: '/assets/flags/bn.svg',
    phoneCode: '+673',
  },
  {
    fullname: 'Bulgaria',
    shortName: 'BGR',
    flag: '/assets/flags/bg.svg',
    phoneCode: '+359',
  },
  {
    fullname: 'Burkina Faso',
    shortName: 'BFA',
    flag: '/assets/flags/bf.svg',
    phoneCode: '+226',
  },
  {
    fullname: 'Burundi',
    shortName: 'BDI',
    flag: '/assets/flags/bi.svg',
    phoneCode: '+257',
  },
  {
    fullname: 'Cabo Verde',
    shortName: 'CV',
    flag: '/assets/flags/cv.svg',
    phoneCode: '+238',
  },
  {
    fullname: 'Cambodia',
    shortName: 'KHM',
    flag: '/assets/flags/kh.svg',
    phoneCode: '+855',
  },
  {
    fullname: 'Cameroon',
    shortName: 'CMR',
    flag: '/assets/flags/cm.svg',
    phoneCode: '+273',
  },
  {
    fullname: 'Canada',
    shortName: 'CAN',
    flag: '/assets/flags/ca.svg',
    phoneCode: '+1',
  },
  {
    fullname: 'Cayman Islands',
    shortName: 'CYM',
    flag: '/assets/flags/ky.svg',
    phoneCode: '+1 345',
  },
  {
    fullname: 'Central African Republic',
    shortName: 'CAF',
    flag: '/assets/flags/cf.svg',
    phoneCode: '+236',
  },
  {
    fullname: 'Chad',
    shortName: 'TCD',
    flag: '/assets/flags/td.svg',
    phoneCode: '+235',
  },
  {
    fullname: 'Chile',
    shortName: 'CHL',
    flag: '/assets/flags/cl.svg',
    phoneCode: '+56',
  },
  {
    fullname: 'China',
    shortName: 'CHN',
    flag: '/assets/flags/cn.svg',
    phoneCode: '+86',
  },
  {
    fullname: 'Christmas Island',
    shortName: 'CXR',
    flag: '/assets/flags/cx.svg',
    phoneCode: '+61 89164',
  },
  {
    fullname: 'Cocos (Keeling) Islands',
    shortName: 'CCK',
    flag: '/assets/flags/cc.svg',
    phoneCode: '+61 89162',
  },
  {
    fullname: 'Colombia',
    shortName: 'COL',
    flag: '/assets/flags/co.svg',
    phoneCode: '+57',
  },
  {
    fullname: 'Comoros',
    shortName: 'COM',
    flag: '/assets/flags/km.svg',
    phoneCode: '+269',
  },
  {
    fullname: 'Cook Islands',
    shortName: 'COK',
    flag: '/assets/flags/ck.svg',
    phoneCode: '+682',
  },
  {
    fullname: 'Costa Rica',
    shortName: 'CRI',
    flag: '/assets/flags/cr.svg',
    phoneCode: '+506',
  },
  {
    fullname: 'Croatia',
    shortName: 'HRV',
    flag: '/assets/flags/hr.svg',
    phoneCode: '+385',
  },
  {
    fullname: 'Cuba',
    shortName: 'CUB',
    flag: '/assets/flags/cu.svg',
    phoneCode: '+53',
  },
  {
    fullname: 'Curacao',
    shortName: 'CW',
    flag: '/assets/flags/cw.svg',
    phoneCode: '+559 9',
  },
  {
    fullname: 'Cyprus',
    shortName: 'CYP',
    flag: '/assets/flags/cy.svg',
    phoneCode: '+357',
  },
  {
    fullname: 'Czech Republic',
    shortName: 'CZE',
    flag: '/assets/flags/cz.svg',
    phoneCode: '+420',
  },
  {
    fullname: "Cote d'Ivoire",
    shortName: 'CIV',
    flag: '/assets/flags/ci.svg',
    phoneCode: '+225',
  },
  {
    fullname: 'Democratic Republic',
    shortName: 'CD',
    flag: '/assets/flags/cd.svg',
    phoneCode: '', //******* NOT THERE ************** */
  },
  {
    fullname: 'Denmark',
    shortName: 'DNK',
    flag: '/assets/flags/dk.svg',
    phoneCode: '+45',
  },
  {
    fullname: 'Djibouti',
    shortName: 'DJI',
    flag: '/assets/flags/dj.svg',
    phoneCode: '+253',
  },
  {
    fullname: 'Dominica',
    shortName: 'DMA',
    flag: '/assets/flags/dm.svg',
    phoneCode: '+1 767',
  },
  {
    fullname: 'Dominician Republic',
    shortName: 'DOM',
    flag: '/assets/flags/do.svg',
    phoneCode: '+1 809',
  },
  {
    fullname: 'Ecuador',
    shortName: 'ECU',
    flag: '/assets/flags/ec.svg',
    phoneCode: '+593',
  },
  {
    fullname: 'Egypt',
    shortName: 'EGY',
    flag: '/assets/flags/eg.svg',
    phoneCode: '+20',
  },
  {
    fullname: 'El Salvador',
    shortName: 'SLV',
    flag: '/assets/flags/sv.svg',
    phoneCode: '+503',
  },
  {
    fullname: 'Equatorial Guinea',
    shortName: 'GNQ',
    flag: '/assets/flags/gq.svg',
    phoneCode: '+240',
  },
  {
    fullname: 'Eritrea',
    shortName: 'ERI',
    flag: '/assets/flags/er.svg',
    phoneCode: '+291',
  },
  {
    fullname: 'Estonia',
    shortName: 'EST',
    flag: '/assets/flags/ee.svg',
    phoneCode: '+372',
  },
  {
    fullname: 'Eswatini',
    shortName: 'SZ',
    flag: '/assets/flags/sz.svg',
    phoneCode: '+268',
  },
  {
    fullname: 'Ethiopia',
    shortName: 'ETH',
    flag: '/assets/flags/et.svg',
    phoneCode: '+251',
  },
  {
    fullname: 'Falkland Islands (Malvinas)',
    shortName: 'FLK',
    flag: '/assets/flags/fk.svg',
    phoneCode: '+500',
  },
  {
    fullname: 'Faroe Islands',
    shortName: 'FRO',
    flag: '/assets/flags/fo.svg',
    phoneCode: '+298',
  },
  {
    fullname: 'Federated States',
    shortName: 'FM',
    flag: '/assets/flags/fm.svg',
    phoneCode: '', ///******* NOT THERE ************** */
  },
  {
    fullname: 'Fiji',
    shortName: 'FJI',
    flag: '/assets/flags/fj.svg',
    phoneCode: '+679',
  },
  {
    fullname: 'Finland',
    shortName: 'FIN',
    flag: '/assets/flags/fi.svg',
    phoneCode: '+358',
  },
  {
    fullname: 'France',
    shortName: 'FRA',
    flag: '/assets/flags/fr.svg',
    phoneCode: '+33',
  },
  {
    fullname: 'French Guiana',
    shortName: 'GUF',
    flag: '/assets/flags/gf.svg',
    phoneCode: '+594',
  },
  {
    fullname: 'French Polynesia',
    shortName: 'PYF',
    flag: '/assets/flags/pf.svg',
    phoneCode: '+689',
  },
  {
    fullname: 'French Southern Territories ',
    shortName: 'ATF',
    flag: '/assets/flags/tf.svg',
    phoneCode: '', //******* NOT THERE ************** */
  },
  {
    fullname: 'Gabon',
    shortName: 'GAB',
    flag: '/assets/flags/ga.svg',
    phoneCode: '+241',
  },
  {
    fullname: 'Gambia',
    shortName: 'GMB',
    flag: '/assets/flags/gm.svg',
    phoneCode: '+220',
  },
  {
    fullname: 'Georgia',
    shortName: 'GEO',
    flag: '/assets/flags/ge.svg',
    phoneCode: '+995',
  },
  {
    fullname: 'Germany',
    shortName: 'DEU',
    flag: '/assets/flags/de.svg',
    phoneCode: '+49',
  },
  {
    fullname: 'Ghana',
    shortName: 'GHA',
    flag: '/assets/flags/gh.svg',
    phoneCode: '+233',
  },
  {
    fullname: 'Gibraltar',
    shortName: 'GIB',
    flag: '/assets/flags/gi.svg',
    phoneCode: '+350',
  },
  {
    fullname: 'Greece',
    shortName: 'GRC',
    flag: '/assets/flags/gr.svg',
    phoneCode: '+30',
  },
  {
    fullname: 'Greenland',
    shortName: 'GRL',
    flag: '/assets/flags/gl.svg',
    phoneCode: '+299',
  },
  {
    fullname: 'Grenada',
    shortName: 'GRD',
    flag: '/assets/flags/gd.svg',
    phoneCode: '+1 473',
  },
  {
    fullname: 'Guadeloupe',
    shortName: 'GLP',
    flag: '/assets/flags/gp.svg',
    phoneCode: '+590',
  },
  {
    fullname: 'Guam',
    shortName: 'GUM',
    flag: '/assets/flags/gu.svg',
    phoneCode: '+1 671',
  },
  {
    fullname: 'Guatemala',
    shortName: 'GTM',
    flag: '/assets/flags/gt.svg',
    phoneCode: '+502',
  },
  {
    fullname: 'Guernsey',
    shortName: 'GGY',
    flag: '/assets/flags/gg.svg',
    phoneCode: '+44 1481',
  },
  {
    fullname: 'Guinea',
    shortName: 'GIN',
    flag: '/assets/flags/gn.svg',
    phoneCode: '+224',
  },
  {
    fullname: 'Guinea Bissau',
    shortName: 'GW',
    flag: '/assets/flags/gw.svg',
    phoneCode: '+245',
  },
  {
    fullname: 'Guyana',
    shortName: 'GUY',
    flag: '/assets/flags/gy.svg',
    phoneCode: '+592',
  },
  {
    fullname: 'Haiti',
    shortName: 'HTI',
    flag: '/assets/flags/ht.svg',
    phoneCode: '+509',
  },
  {
    fullname: 'Heard and Mcdonald Islands',
    shortName: 'HMD',
    flag: '/assets/flags/hm.svg',
    phoneCode: '', //******* NOT THERE ************** */
  },
  {
    fullname: 'Holy See (Vatican City State)',
    shortName: 'VAT',
    flag: '/assets/flags/va.svg',
    phoneCode: '', //******* NOT THERE ************** */
  },
  {
    fullname: 'Honduras',
    shortName: 'HND',
    flag: '/assets/flags/hn.svg',
    phoneCode: '+504',
  },
  {
    fullname: 'Hong Kong',
    shortName: 'HK',
    flag: '/assets/flags/hk.svg',
    phoneCode: '+852',
  },
  {
    fullname: 'Hungary',
    shortName: 'HUN',
    flag: '/assets/flags/hu.svg',
    phoneCode: '+36',
  },
  {
    fullname: 'Iceland',
    shortName: 'ISL',
    flag: '/assets/flags/is.svg',
    phoneCode: '+354',
  },
  {
    fullname: 'India',
    shortName: 'IND',
    flag: '/assets/flags/in.svg',
    phoneCode: '+91',
  },
  {
    fullname: 'Indonesia',
    shortName: 'IDN',
    flag: '/assets/flags/id.svg',
    phoneCode: '+62',
  },
  {
    fullname: 'Iran',
    shortName: 'IRN',
    flag: '/assets/flags/ir.svg',
    phoneCode: '+98',
  },
  {
    fullname: 'Iraq',
    shortName: 'IRQ',
    flag: '/assets/flags/iq.svg',
    phoneCode: '+964',
  },
  {
    fullname: 'Ireland',
    shortName: 'IRL',
    flag: '/assets/flags/ie.svg',
    phoneCode: '+353',
  },
  {
    fullname: 'Isle of Man',
    shortName: 'IMN',
    flag: '/assets/flags/im.svg',
    phoneCode: '+44 7924',
  },
  {
    fullname: 'Israel',
    shortName: 'ISR',
    flag: '/assets/flags/il.svg',
    phoneCode: '+972',
  },
  {
    fullname: 'Italy',
    shortName: 'ITA',
    flag: '/assets/flags/it.svg',
    phoneCode: '+39',
  },
  {
    fullname: 'Jamaica',
    shortName: 'JAM',
    flag: '/assets/flags/jm.svg',
    phoneCode: '+1 658',
  },
  {
    fullname: 'Japan',
    shortName: 'JPN',
    flag: '/assets/flags/jp.svg',
    phoneCode: '+81',
  },
  {
    fullname: 'Jersey',
    shortName: 'JEY',
    flag: '/assets/flags/je.svg',
    phoneCode: '+44 1534',
  },
  {
    fullname: 'Jordan',
    shortName: 'JOR',
    flag: '/assets/flags/jo.svg',
    phoneCode: '+962',
  },
  {
    fullname: 'Kazakhstan',
    shortName: 'KAZ',
    flag: '/assets/flags/kz.svg',
    phoneCode: '+76',
  },
  {
    fullname: 'Kenya',
    shortName: 'KEN',
    flag: '/assets/flags/ke.svg',
    phoneCode: '+254',
  },
  {
    fullname: 'Kiribati',
    shortName: 'KIR',
    flag: '/assets/flags/ki.svg',
    phoneCode: '+686',
  },
  {
    fullname: 'Kuwait',
    shortName: 'KWT',
    flag: '/assets/flags/kw.svg',
    phoneCode: '+965',
  },
  {
    fullname: 'Kyrgyztan',
    shortName: 'KGZ',
    flag: '/assets/flags/kg.svg',
    phoneCode: '+996',
  },
  {
    fullname: 'Laos',
    shortName: 'LAO',
    flag: '/assets/flags/la.svg',
    phoneCode: '+856',
  },
  {
    fullname: 'Latvia',
    shortName: 'LVA',
    flag: '/assets/flags/lv.svg',
    phoneCode: '+371',
  },
  {
    fullname: 'Lebanon',
    shortName: 'LBN',
    flag: '/assets/flags/lb.svg',
    phoneCode: '+961',
  },
  {
    fullname: 'Lesotho',
    shortName: 'LSO',
    flag: '/assets/flags/ls.svg',
    phoneCode: '+266',
  },
  {
    fullname: 'Liberia',
    shortName: 'LBR',
    flag: '/assets/flags/lr.svg',
    phoneCode: '+231',
  },
  {
    fullname: 'Libya',
    shortName: 'LBY',
    flag: '/assets/flags/ly.svg',
    phoneCode: '+218',
  },
  {
    fullname: 'Liechtenstein',
    shortName: 'LIE',
    flag: '/assets/flags/li.svg',
    phoneCode: '+423',
  },
  {
    fullname: 'Lithuania',
    shortName: 'LTU',
    flag: '/assets/flags/lt.svg',
    phoneCode: '+370',
  },
  {
    fullname: 'Luxembourg',
    shortName: 'LUX',
    flag: '/assets/flags/lu.svg',
    phoneCode: '+352',
  },
  {
    fullname: 'Macedonia',
    shortName: 'MKD',
    flag: '/assets/flags/mo.svg',
    phoneCode: '', //******* NOT THERE ************** */
  },
  {
    fullname: 'Madagascar',
    shortName: 'MDG',
    flag: '/assets/flags/mg.svg',
    phoneCode: '+261',
  },
  {
    fullname: 'Malawi',
    shortName: 'MWI',
    flag: '/assets/flags/mw.svg',
    phoneCode: '+265',
  },
  {
    fullname: 'Malaysia',
    shortName: 'MYS',
    flag: '/assets/flags/my.svg',
    phoneCode: '+60',
  },
  {
    fullname: 'Maldives',
    shortName: 'MDV',
    flag: '/assets/flags/mv.svg',
    phoneCode: '+960',
  },
  {
    fullname: 'Mali',
    shortName: 'MLI',
    flag: '/assets/flags/ml.svg',
    phoneCode: '+223',
  },
  {
    fullname: 'Malta',
    shortName: 'MLT',
    flag: '/assets/flags/mt.svg',
    phoneCode: '+356',
  },
  {
    fullname: 'Marshall Islands',
    shortName: 'MHL',
    flag: '/assets/flags/mh.svg',
    phoneCode: '+692',
  },
  {
    fullname: 'Martinique',
    shortName: 'MTQ',
    flag: '/assets/flags/mq.svg',
    phoneCode: '+596',
  },
  {
    fullname: 'Mauritania',
    shortName: 'MRT',
    flag: '/assets/flags/mr.svg',
    phoneCode: '+222',
  },
  {
    fullname: 'Mauritius',
    shortName: 'MUS',
    flag: '/assets/flags/mu.svg',
    phoneCode: '+230',
  },
  {
    fullname: 'Mayotte',
    shortName: 'MYT',
    flag: '/assets/flags/yt.svg',
    phoneCode: '+262 639',
  },
  {
    fullname: 'Mexico',
    shortName: 'MEX',
    flag: '/assets/flags/mx.svg',
    phoneCode: '+52',
  },
  {
    fullname: 'Moldova',
    shortName: 'MDA',
    flag: '/assets/flags/md.svg',
    phoneCode: '+373',
  },
  {
    fullname: 'Monaco',
    shortName: 'MCO',
    flag: '/assets/flags/mc.svg',
    phoneCode: '+377',
  },
  {
    fullname: 'Mongolia',
    shortName: 'MNG',
    flag: '/assets/flags/mn.svg',
    phoneCode: '+976',
  },
  {
    fullname: 'Montenegro',
    shortName: 'MNE',
    flag: '/assets/flags/me.svg',
    phoneCode: '+382',
  },
  {
    fullname: 'Montserrat',
    shortName: 'MSR',
    flag: '/assets/flags/ms.svg',
    phoneCode: '+1 664',
  },
  {
    fullname: 'Morocco',
    shortName: 'MAR',
    flag: '/assets/flags/ma.svg',
    phoneCode: '+212',
  },
  {
    fullname: 'Mozambique',
    shortName: 'MOZ',
    flag: '/assets/flags/mz.svg',
    phoneCode: '+258',
  },
  {
    fullname: 'Myanmar',
    shortName: 'MMR',
    flag: '/assets/flags/mm.svg',
    phoneCode: '+95',
  },
  {
    fullname: 'Namibia',
    shortName: 'NAM',
    flag: '/assets/flags/na.svg',
    phoneCode: '+264',
  },
  {
    fullname: 'Nauru',
    shortName: 'NRU',
    flag: '/assets/flags/nr.svg',
    phoneCode: '+674',
  },
  {
    fullname: 'Nepal',
    shortName: 'NPL',
    flag: '/assets/flags/np.svg',
    phoneCode: '+977',
  },
  {
    fullname: 'Netherlands',
    shortName: 'NLD',
    flag: '/assets/flags/nl.svg',
    phoneCode: '+31',
  },
  {
    fullname: 'New Caledonia',
    shortName: 'NCL',
    flag: '/assets/flags/nc.svg',
    phoneCode: '+687',
  },
  {
    fullname: 'New Zealand',
    shortName: 'NZL',
    flag: '/assets/flags/nz.svg',
    phoneCode: '+64',
  },
  {
    fullname: 'Nicaragua',
    shortName: 'NIC',
    flag: '/assets/flags/na.svg',
    phoneCode: '+505',
  },
  {
    fullname: 'Niger',
    shortName: 'NER',
    flag: '/assets/flags/ne.svg',
    phoneCode: '+227',
  },
  {
    fullname: 'Nigeria',
    shortName: 'NGA',
    flag: '/assets/flags/ng.svg',
    phoneCode: '+234',
  },
  {
    fullname: 'Niue',
    shortName: 'NIU',
    flag: '/assets/flags/nu.svg',
    phoneCode: '+683',
  },
  {
    fullname: 'Norfolk Island',
    shortName: 'NFK',
    flag: '/assets/flags/nf.svg',
    phoneCode: '+672 3',
  },
  {
    fullname: 'North Korea',
    shortName: 'KP',
    flag: '/assets/flags/kp.svg',
    phoneCode: '+850',
  },
  {
    fullname: 'North Macedonia',
    shortName: 'MK',
    flag: '/assets/flags/mk.svg',
    phoneCode: '+389',
  },
  {
    fullname: 'North Mariana Islands.',
    shortName: 'MNP',
    flag: '/assets/flags/mp.svg',
    phoneCode: '+1 670',
  },
  {
    fullname: 'Norway',
    shortName: 'NOR',
    flag: '/assets/flags/no.svg',
    phoneCode: '+47',
  },
  {
    fullname: 'Oman',
    shortName: 'OM',
    flag: '/assets/flags/om.svg',
    phoneCode: '+968',
  },
  {
    fullname: 'Pakistan',
    shortName: 'PK',
    flag: '/assets/flags/pk.svg',
    phoneCode: '+92',
  },
  {
    fullname: 'Palau',
    shortName: 'PW',
    flag: '/assets/flags/pw.svg',
    phoneCode: '+680',
  },
  {
    fullname: 'Panama',
    shortName: 'PA',
    flag: '/assets/flags/pa.svg',
    phoneCode: '+507',
  },
  {
    fullname: 'Papua New Guinea',
    shortName: 'PG',
    flag: '/assets/flags/pg.svg',
    phoneCode: '+675',
  },
  {
    fullname: 'Paraguay',
    shortName: 'PY',
    flag: '/assets/flags/py.svg',
    phoneCode: '+595',
  },
  {
    fullname: 'Peru',
    shortName: 'PE',
    flag: '/assets/flags/pe.svg',
    phoneCode: '+51',
  },
  {
    fullname: 'Philippines',
    shortName: 'PH',
    flag: '/assets/flags/ph.svg',
    phoneCode: '+63',
  },
  {
    fullname: 'Pitcaim Islands',
    shortName: 'PN',
    flag: '/assets/flags/pn.svg',
    phoneCode: '+64',
  },
  {
    fullname: 'Poland',
    shortName: 'PL',
    flag: '/assets/flags/pl.svg',
    phoneCode: '+48',
  },
  {
    fullname: 'Portugal',
    shortName: 'PT',
    flag: '/assets/flags/pt.svg',
    phoneCode: '+351',
  },
  {
    fullname: 'Puerto Rico',
    shortName: 'PR',
    flag: '/assets/flags/pr.svg',
    phoneCode: '+1 939',
  },
  {
    fullname: 'Qatar',
    shortName: 'QA',
    flag: '/assets/flags/qa.svg',
    phoneCode: '+974',
  },
  {
    fullname: 'Republic of the Co...',
    shortName: 'CG',
    flag: '/assets/flags/cg.svg',
    phoneCode: '', //******* NOT THERE ************** */
  },
  {
    fullname: 'Romania',
    shortName: 'RO',
    flag: '/assets/flags/ro.svg',
    phoneCode: '+40',
  },
  {
    fullname: 'Russia',
    shortName: 'RU',
    flag: '/assets/flags/ru.svg',
    phoneCode: '+7',
  },
  {
    fullname: 'Rwanda',
    shortName: 'RW',
    flag: '/assets/flags/rw.svg',
    phoneCode: '+250',
  },
  {
    fullname: 'Reunion',
    shortName: 'RE',
    flag: '/assets/flags/re.svg',
    phoneCode: '+262',
  },
  {
    fullname: 'Saint Barthelemy',
    shortName: 'BL',
    flag: '/assets/flags/bl.svg',
    phoneCode: '+590',
  },
  {
    fullname: 'Saint Helena',
    shortName: 'SH',
    flag: '/assets/flags/sh.svg',
    phoneCode: '+290',
  },
  {
    fullname: 'Saint Kitts and Nevis',
    shortName: 'KN',
    flag: '/assets/flags/kn.svg',
    phoneCode: '+1 869',
  },
  {
    fullname: 'Saint Lucia',
    shortName: 'LC',
    flag: '/assets/flags/lc.svg',
    phoneCode: '+1758',
  },
  {
    fullname: 'Saint Martin (France)',
    shortName: 'MF',
    flag: '/assets/flags/mf.svg',
    phoneCode: '+590',
  },
  {
    fullname: 'Saint Pierre and Miquelon',
    shortName: 'PM',
    flag: '/assets/flags/pm.svg',
    phoneCode: ' +508',
  },
  {
    fullname: 'Saint Vincent and the Grenadines',
    shortName: 'VC',
    flag: '/assets/flags/vc.svg',
    phoneCode: '+1784',
  },
  {
    fullname: 'Samoa',
    shortName: 'WS',
    flag: '/assets/flags/ws.svg',
    phoneCode: '+685',
  },
  {
    fullname: 'San Marino',
    shortName: 'SM',
    flag: '/assets/flags/sm.svg',
    phoneCode: '+378',
  },
  {
    fullname: 'Sao Tome and Principe',
    shortName: 'ST',
    flag: '/assets/flags/st.svg',
    phoneCode: '+239',
  },
  {
    fullname: 'Saudi Arabia',
    shortName: 'SA',
    flag: '/assets/flags/sa.svg',
    phoneCode: '+966',
  },
  {
    fullname: 'Sengal',
    shortName: 'SN',
    flag: '/assets/flags/sn.svg',
    phoneCode: '+221',
  },
  {
    fullname: 'Serbia',
    shortName: 'RS',
    flag: '/assets/flags/rs.svg',
    phoneCode: '+381',
  },
  {
    fullname: 'Seychelles',
    shortName: 'SC',
    flag: '/assets/flags/sc.svg',
    phoneCode: '+248',
  },
  {
    fullname: 'Sierra Leone',
    shortName: 'SL',
    flag: '/assets/flags/sl.svg',
    phoneCode: '+232',
  },
  {
    fullname: 'Singapore',
    shortName: 'SG',
    flag: '/assets/flags/sg.svg',
    phoneCode: '+65',
  },
  {
    fullname: 'Sint Maarten (Netherlands)',
    shortName: 'SX',
    flag: '/assets/flags/sx.svg',
    phoneCode: '+1721',
  },
  {
    fullname: 'Slovakia',
    shortName: 'SK',
    flag: '/assets/flags/sk.svg',
    phoneCode: '+421',
  },
  {
    fullname: 'Slovenia',
    shortName: 'Si',
    flag: '/assets/flags/si.svg',
    phoneCode: '+386',
  },
  {
    fullname: 'Solomon Islands',
    shortName: 'SB',
    flag: '/assets/flags/sb.svg',
    phoneCode: '+677',
  },
  {
    fullname: 'Somalia',
    shortName: 'SO',
    flag: '/assets/flags/so.svg',
    phoneCode: '+252',
  },
  {
    fullname: 'South Africa',
    shortName: 'ZA',
    flag: '/assets/flags/za.svg',
    phoneCode: '+27',
  },
  {
    fullname: 'South Georgia',
    shortName: 'GS',
    flag: '/assets/flags/gs.svg',
    phoneCode: '',
  },
  {
    fullname: 'South Korea',
    shortName: 'KR',
    flag: '/assets/flags/kr.svg',
    phoneCode: '+500',
  },
  {
    fullname: 'South Sudan',
    shortName: 'SS',
    flag: '/assets/flags/ss.svg',
    phoneCode: '+211',
  },
  {
    fullname: 'Spain',
    shortName: 'ES',
    flag: '/assets/flags/es.svg',
    phoneCode: '+34',
  },
  {
    fullname: 'Sri Lanka',
    shortName: 'LK',
    flag: '/assets/flags/lk.svg',
    phoneCode: '+94',
  },
  {
    fullname: 'State of Palestine',
    shortName: 'PS',
    flag: '/assets/flags/ps.svg',
    phoneCode: '', //******* NOT THERE ************** */
  },
  {
    fullname: 'Sudan',
    shortName: 'SD',
    flag: '/assets/flags/sd.svg',
    phoneCode: '+294',
  },
  {
    fullname: 'Suriname',
    shortName: 'SR',
    flag: '/assets/flags/sr.svg',
    phoneCode: '+597',
  },
  {
    fullname: 'Svalbard and Jan',
    shortName: 'SJ',
    flag: '/assets/flags/sj.svg',
    phoneCode: '+4779',
  },
  {
    fullname: 'Sweden',
    shortName: 'SE',
    flag: '/assets/flags/se.svg',
    phoneCode: '+46',
  },
  {
    fullname: 'Switzerland',
    shortName: 'CH',
    flag: '/assets/flags/ch.svg',
    phoneCode: '+41',
  },
  {
    fullname: 'Syria',
    shortName: 'SY',
    flag: '/assets/flags/sy.svg',
    phoneCode: '+963',
  },
  {
    fullname: 'Taiwan',
    shortName: 'tw',
    flag: '/assets/flags/tw.svg',
    phoneCode: '+886',
  },
  {
    fullname: 'Tajikistan',
    shortName: 'TJ',
    flag: '/assets/flags/tj.svg',
    phoneCode: '+992',
  },
  {
    fullname: 'Tanzania',
    shortName: 'TZ',
    flag: '/assets/flags/tz.svg',
    phoneCode: '+255',
  },
  {
    fullname: 'Thailand',
    shortName: 'th',
    flag: '/assets/flags/th.svg',
    phoneCode: '+66',
  },
  {
    fullname: 'East Timor (Timor Leste)',
    shortName: 'TL',
    flag: '/assets/flags/tl.svg',
    phoneCode: '+670',
  },
  {
    fullname: 'Togo',
    shortName: 'tg',
    flag: '/assets/flags/tg.svg',
    phoneCode: '+228',
  },
  {
    fullname: 'Tokelau',
    shortName: 'TK',
    flag: '/assets/flags/tk.svg',
    phoneCode: '+690',
  },
  {
    fullname: 'Tonga',
    shortName: 'to',
    flag: '/assets/flags/to.svg',
    phoneCode: '+676',
  },
  {
    fullname: 'Trinidad and Tobago',
    shortName: 'TT',
    flag: '/assets/flags/tt.svg',
    phoneCode: '+1868',
  },
  {
    fullname: 'Tunisia',
    shortName: 'tn',
    flag: '/assets/flags/tn.svg',
    phoneCode: '+216',
  },
  {
    fullname: 'Turkey',
    shortName: 'tr',
    flag: '/assets/flags/tr.svg',
    phoneCode: '+90',
  },
  {
    fullname: 'Turkmenistan',
    shortName: 'TM',
    flag: '/assets/flags/tm.svg',
    phoneCode: '+993',
  },
  {
    fullname: 'Turks and Caicos Island',
    shortName: 'TC',
    flag: '/assets/flags/tc.svg',
    phoneCode: '+1649',
  },
  {
    fullname: 'Tuvalu',
    shortName: 'TV',
    flag: '/assets/flags/tv.svg',
    phoneCode: '+688',
  },
  {
    fullname: 'Uganda',
    shortName: 'UG',
    flag: '/assets/flags/ug.svg',
    phoneCode: '+256',
  },
  {
    fullname: 'Ukraine',
    shortName: 'UA',
    flag: '/assets/flags/ua.svg',
    phoneCode: '+380',
  },
  {
    fullname: 'United Arab Emirates',
    shortName: 'AE',
    flag: '/assets/flags/ae.svg',
    phoneCode: '+971',
  },
  {
    fullname: 'United Kingdom',
    shortName: 'GB',
    flag: '/assets/flags/gb.svg',
    phoneCode: '+44',
  },
  {
    fullname: 'United States Minisota',
    shortName: 'UM',
    flag: '/assets/flags/um.svg',
    phoneCode: '', //******* NOT THERE ************** */
  },
  {
    fullname: 'United States of America',
    shortName: 'US',
    flag: '/assets/flags/us.svg',
    phoneCode: '+1808',
  },
  {
    fullname: 'Uruguay',
    shortName: 'UY',
    flag: '/assets/flags/uy.svg',
    phoneCode: '+598',
  },
  {
    fullname: 'Uzbekistan',
    shortName: 'UZ',
    flag: '/assets/flags/uz.svg',
    phoneCode: '+998',
  },
  {
    fullname: 'Vanuatu',
    shortName: 'VU',
    flag: '/assets/flags/vu.svg',
    phoneCode: '+678',
  },
  {
    fullname: 'Venezuela',
    shortName: 'VE',
    flag: '/assets/flags/ve.svg',
    phoneCode: '+58',
  },
  {
    fullname: 'Vietnam',
    shortName: 'VN',
    flag: '/assets/flags/vn.svg',
    phoneCode: '+84',
  },
  {
    fullname: 'Virgin Islands (British)',
    shortName: 'VG',
    flag: '/assets/flags/vg.svg',
    phoneCode: '', //******* NOT THERE ************** */
  },
  {
    fullname: 'Virgin Islands (US)',
    shortName: 'VI',
    flag: '/assets/flags/vi.svg',
    phoneCode: '+1340',
  },
  {
    fullname: 'Wallis and Futuna',
    shortName: 'WF',
    flag: '/assets/flags/wf.svg',
    phoneCode: '+681',
  },
  {
    fullname: 'Western Sahara',
    shortName: 'EH',
    flag: '/assets/flags/eh.svg',
    phoneCode: '', //******* NOT THERE ************** */
  },
  {
    fullname: 'Yemen',
    shortName: 'YE',
    flag: '/assets/flags/ye.svg',
    phoneCode: '+967',
  },
  {
    fullname: 'Zambia',
    shortName: 'ZM',
    flag: '/assets/flags/zm.svg',
    phoneCode: '+260',
  },
  {
    fullname: 'Zimbabwe',
    shortName: 'ZW',
    flag: '/assets/flags/zw.svg',
    phoneCode: '+263',
  },
  {
    fullname: 'Ascension Island',
    shortName: 'AC',
    flag: '/assets/flags/ac.svg',
    phoneCode: '+247',
  },
  {
    fullname: 'Canary Islands',
    shortName: 'IC',
    flag: '/assets/flags/ic.svg',
    phoneCode: '',
  },
  {
    fullname: 'Catalonia',
    shortName: 'ES-CT',
    flag: '/assets/flags/es-ct.svg',
    phoneCode: '',
  },
  {
    fullname: 'Central European',
    shortName: 'CEFTA',
    flag: '/assets/flags/cefta.svg',
    phoneCode: '',
  },
  {
    fullname: 'Ceuta & Melilla',
    shortName: 'EA',
    flag: '/assets/flags/ea.svg',
    phoneCode: '',
  },
  {
    fullname: 'Clipperton Island',
    shortName: 'CP',
    flag: '/assets/flags/cp.svg',
    phoneCode: '',
  },
  {
    fullname: 'Diego Garcia',
    shortName: 'DG',
    flag: '/assets/flags/dg.svg',
    phoneCode: '+246',
  },
  {
    fullname: 'England',
    shortName: 'GB-ENG',
    flag: '/assets/flags/gb-eng.svg',
    phoneCode: '',
  },
  {
    fullname: 'Europe',
    shortName: 'EU',
    flag: '/assets/flags/eu.svg',
    phoneCode: '',
  },
  {
    fullname: 'Galicia',
    shortName: 'ES-GA',
    flag: '/assets/flags/es-ga.svg',
    phoneCode: '',
  },
  {
    fullname: 'Kosovo',
    shortName: 'XK',
    flag: '/assets/flags/xk.svg',
    phoneCode: '',
  },
  {
    fullname: 'Northern Ireland',
    shortName: 'GB-NIR',
    flag: '/assets/flags/gb-nir.svg',
    phoneCode: '+4428',
  },
  {
    fullname: 'Scotland',
    shortName: 'GB-SCT',
    flag: '/assets/flags/gb-sct.svg',
    phoneCode: '',
  },
  {
    fullname: 'Tristan da Cunha',
    shortName: 'TA',
    flag: '/assets/flags/ta.svg',
    phoneCode: '',
  },
  {
    fullname: 'United Nations',
    shortName: 'UN',
    flag: '/assets/flags/un.svg',
    phoneCode: '',
  },
  {
    fullname: 'Unknown',
    shortName: 'XX',
    flag: '/assets/flags/xx.svg',
    phoneCode: '',
  },
  {
    fullname: 'Wales',
    shortName: 'GB-WLS',
    flag: '/assets/flags/gb-wls.svg',
    phoneCode: '',
  },

];
